function fns = stimFields()

fns = {'startTime', ...
    'endTime', ...
    'stimstart', ...
    'msgs', ...
    'ori1', ...
    'ori2', ...
    'stimbefore', ...
    'preStimFix', ...
    'fixXpos', ...
    'fixYpos', ...
    'GlobalTrialNumber', ...
    'IsInstruction', ...
    'IsCatchTrial', ...
    'IsValid', ...
    'ChangeLocation', ...
    'Outcome', ...
    'StimBefore', ...
    'MaxStimBefore', ...
    'AttentionLocation', ...
    'TargetFixation', ...
    'Contrast', ...
    'Orientation', ...
    'OrientationChange', ...
    'ThisOrientationChange', ...
    'Phase', ...
    'SpatialFrequency', ...
    'PhaseVelocity', ...
    'StimulusX', ...
    'StimulusY', ...
    'Radius', ...
    'FixX', ...
    'FixY', ...
    'ISI', ...
    'StimulusDuration', ...
    'RT', ...
    'ChangeDegList', ...
    'IsInstructionList', ...
    'IsValidList', ...
    'ChangeLocationList', ...
    'BlockTrialCount', ...
    'BlockNumber', ...
    'outcome'};

end
